### PR TITLE
KOGITO-1628: Cucumber tests: Merge the way we handle services into the test framework

### PR DESCRIPTION
**Pull request by Sgitario**
JIRA Ticket: https://issues.redhat.com/browse/KOGITO-1628
Description: Since the merge of handling the services (data-index, jobs-service, management-console) as a generic implementation on operator's side, we could do it as well on test framework.

Solution: 

We'll be providing a couple of types:
- ProtoKogitoService (kogitobaseservice.go): For common Openshift services
- ProtoKogitoInstallService (kogitoinstallbaseservice.go): For installation utilities

Many thanks for submiting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.MD#sending-a-pull-request)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Comment by sutaakar** [comment]
@Sgitario Why there is a need for new types?
Could we just reuse existing ones?

**Comment by sutaakar** [comment]
All those components (KogitoDataIndex, KogitoJobsService...) implement method for retrieving spec, we can reuse this and operate against all components using one interface defining that method. That is just a suggestion.

**Comment by Sgitario** [comment]
The problem is that the spec is a sepatate type and this is auto generated, so we cannot modify to either add an interface or reuse methods. 

These two new types try to amend this problem and create a tree classes to add common funcionality (which was the purpose of the refactor). However, if you see any other approach, let me know.

**Comment by sutaakar** [comment]
I meant something like https://github.com/sutaakar/kogito-cloud-operator/commit/05e272e09e68d3daab97644935d47f0c887bff88 (just an example)

Though there may be other ways to unify the implementation....

**Comment by sutaakar** [comment]
What I meant is this, what are the common methods which we should unify?

For example https://github.com/kiegroup/kogito-cloud-operator/blob/master/test/framework/kogitodataindex.go#L96 , what is the difference between Data index and Jobs service for these methods? Just deployment name. So we can define the deployment name as a parameter and unify the method implementation.

**Comment by sutaakar** [comment]
Or for example https://github.com/kiegroup/kogito-cloud-operator/blob/master/test/framework/kogitojobsservice.go#L110 , what is the difference betweeb Jobs service and Data index for such method? Just service name. So what about putting the service name as a parameter?

**Comment by Sgitario** [comment]
Exactly this is what I'm trying to address, avoid the duplication of code by having all the common methods in:
- [kogitobaseservice.go](https://github.com/Sgitario/kogito-cloud-operator/pull/1/files#diff-481966e5e1192d4b67ae201e7f2b9158) for common methods
- and for services that requires installation: [kogitoinstallbaseservice.go ](https://github.com/Sgitario/kogito-cloud-operator/pull/1/files#diff-76fa7abc579dfd3747a64fb6a97f28e7)

Perhaps the difference you suggest is that instead of having a hierarchy, we just pass the parameters (either the service name or the deployment name or any other depending to the method). About this subject, I would prefer having "Proto" types, so we have everything in only a single place. 

I will take a look to the link you provided about using existing interfaces: https://github.com/kiegroup/kogito-cloud-operator/blob/master/test/framework/kogitojobsservice.go#L110.

**Comment by sutaakar** [comment]
What is the difference between Proto type service and for example Data index service?

**Comment by sutaakar** [comment]
My intention is to keep the structure as simple as possible.

**Pull request closed without merging**
